apiVersion: v1
kind: Namespace
metadata:
  name: swp-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: echo-nextjs-client
  namespace: swp-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: echo-nextjs-client-container
        image: echo-nextjs-client-image
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: ECHO_SERVICE_URL
            valueFrom:
              secretKeyRef:
                name: echo-service-url
                key: echo_service_url
        envFrom:
          - configMapRef:
              name: echo-nextjs-client-config
---
apiVersion: v1
kind: Service
metadata:
  name: echo-nextjs-client
  namespace: swp-ns
spec:
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: echo-nextjs-client-config
  namespace: swp-ns
data:
  ECHO_SERVICE_GET_PING: ''
  ECHO_SERVICE_POST_ECHO: echo
  ECHO_SERVICE_POST_REVERSE: reverse
  ECHO_SERVICE_GET_ECHOES: echoes
